[project]
name = "resume-ai-insight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "google-genai>=1.74.0",
    "json-repair>=0.59.5",
    "pymupdf>=1.27.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
